# Generated by Django 5.2.15 on 2026-06-23 21:50

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.article_image_path, verbose_name='图片文件')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='图片说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '文章配图',
                'verbose_name_plural': '文章配图',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
