# Generated by Django 5.2.15 on 2026-06-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='subfolder',
            field=models.CharField(blank=True, default='img', help_text='图片存放子目录，默认 img', max_length=100, verbose_name='子目录'),
        ),
    ]
