# Generated by Django 5.2.15 on 2026-06-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articleimage_subfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='subfolder',
        ),
    ]
