# Generated by Django 5.2.7 on 2025-12-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#2196F3', help_text='标签颜色（HEX 格式，例如 #FF5733）', max_length=7, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '技术标签',
                'verbose_name_plural': '技术标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='project.techtag', verbose_name='技术标签')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目展示',
                'ordering': ['-created_at'],
            },
        ),
    ]
