# Generated by Django 5.2.15 on 2026-07-01 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="项目标题")),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="项目简介"),
                ),
                (
                    "bilibili_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Bilibili 视频链接"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, default="", verbose_name="GitHub 开源链接"
                    ),
                ),
                (
                    "started_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="项目开始时间"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["order", "-started_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#5b8cbd",
                        help_text="HEX 格式，例如 #5b8cbd",
                        max_length=7,
                        verbose_name="标签颜色",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目标签",
                "verbose_name_plural": "项目标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文档标题")),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="文档摘要"),
                ),
                ("content", models.TextField(verbose_name="Markdown 内容")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="project.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目文档",
                "verbose_name_plural": "项目文档",
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="project.projecttag",
                verbose_name="项目标签",
            ),
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "happened_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="更新时间"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="更新标题")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="更新说明"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="project.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目更新",
                "verbose_name_plural": "项目更新",
                "ordering": ["-happened_at", "-id"],
            },
        ),
    ]
