# Generated by Django 5.2.15 on 2026-07-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectupdate",
            name="title",
        ),
        migrations.AlterField(
            model_name="projecttag",
            name="color",
            field=models.CharField(
                default="#afcdda",
                help_text="HEX 格式，例如 #5b8cbd",
                max_length=7,
                verbose_name="标签颜色",
            ),
        ),
    ]
