# Generated by Django 5.2.15 on 2026-07-01 04:08

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_projectupdate_title_alter_projecttag_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocumentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=project.models.project_document_image_path,
                        verbose_name="图片文件",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="图片说明"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="project.projectdocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目文档配图",
                "verbose_name_plural": "项目文档配图",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
